---

- block:

  - name: set fcontext for {{ nginx_ssl_cert | dirname }}
    sefcontext:
      target: "{{ nginx_ssl_cert  | dirname }}(/.*)?"
      setype: cert_t
      state: present
    when: not nginx_udpate_only

  - name: apply fcontext to {{ nginx_ssl_cert | dirname }}
    shell: restorecon -irv {{ nginx_ssl_cert  | dirname }}
    register: restorecon_res
    changed_when: restorecon_res.stdout != ""
    when: not nginx_udpate_only



  - name: set fcontext for {{ nginx_default_document_root }}/www
    sefcontext:
      target: "{{ nginx_default_document_root }}(/.*)?/www(/.*)?"
      setype: httpd_sys_script_exec_t
      state: present

  - name: set fcontext for {{ nginx_default_document_root }}/logs
    sefcontext:
      target: "{{ nginx_default_document_root }}(/.*)?/logs(/.*)?"
      setype: httpd_log_t
      state: present

  - name: apply fcontext to {{ nginx_default_document_root }}/www
    shell: restorecon -irv {{ nginx_default_document_root }}
    register: restorecon_res
    changed_when: restorecon_res.stdout != ""



  - name: set fcontext for vhosts (web) with specified documentroot
    sefcontext:
      target: "{{ item.documentroot }}(/.*)?"
      setype: httpd_sys_script_exec_t
      state: present
    with_items: "{{ nginx_vhosts }}"
    when: item.type == 'web' and item.documentroot is defined
    
  - name: set fcontext for vhosts (web) with specified documentroot
    shell: restorecon -irv {{ item.documentroot }}
    register: restorecon_res
    changed_when: restorecon_res.stdout != ""
    with_items: "{{ nginx_vhosts }}"
    when: item.type == 'web' and item.documentroot is defined

  - name: activate selinux bools
    seboolean:
      name: "{{ item }}"
      state: yes
      persistent: yes
    with_items:
    - httpd_enable_cgi
    - httpd_can_network_connect
    - httpd_can_connect_ldap
    - httpd_can_sendmail
    - httpd_execmem
    - httpd_can_network_relay 

  - name: copy custom selinux module
    copy:
      src: uniq_nginx_fix.te
      dest: /tmp/uniq_nginx_fix.te

  - name: compile and activate custom selinux module
    shell: |
      checkmodule -M -m -o /tmp/uniq_nginx_fix.mod /tmp/uniq_nginx_fix.te
      semodule_package -o /tmp/uniq_nginx_fix.pp -m /tmp/uniq_nginx_fix.mod
      semodule -i /tmp/uniq_nginx_fix.pp
    changed: no

  when: nginx_selinux

...




 